### ISSUE TITLE
Re-run .NET implementation (pedrosakuma)

### ISSUE THREAD

**Issue by pedrosakuma** [buybackoff/1brc#10]
Victor, 

When you get the time, could you re-run with my last set of implementations?

https://github.com/pedrosakuma/1brc

Thanks a lot!

**Comment by buybackoff** [comment]
I'm getting 5.503 vs 5.979 in the table.

Will update the table later.

**Comment by pedrosakuma** [comment]
Hey Victor 

I was expecting a more significant improvement, but i guess that maybe it rely on the hardware. 

Thanks anyway!

**Comment by pedrosakuma** [comment]
Hello Victor.

I think this is my last run, made some improvements.
Maybe this time it will show in the execution time.

Thanks in advance.

**Comment by buybackoff** [comment]
Thanks!

BTW, you code cannot finish on this dataset https://github.com/gunnarmorling/1brc/pull/246#issue-2070971816. Or it just take too long, I could not wait for more than 3 minutes.

**Comment by pedrosakuma** [comment]
Thanks for the feedback! 
I didnt know about this generator.

**Comment by buybackoff** [comment]
Could you, please, try to make it work by tomorrow?

**Comment by pedrosakuma** [comment]
It seems to be fixed, but had to rollback some performance improvements that made assumptions over the data. 
But i guess that was the whole point of changing the file. 
Thanks again for pointing that out

**Comment by buybackoff** [comment]
See my blog post. You changes to work with 10K dataset made the default case significantly slower - but valid and accepted :) 

![image](https://github.com/buybackoff/1brc/assets/489852/f41a0646-4dbc-41f4-8496-9d830553c333)
