### ISSUE TITLE
measurements 

### ISSUE THREAD

**Issue by zamgi** [buybackoff/1brc#12]

**Comment by buybackoff** [comment]
Salut!  It's all here: https://hotforknowledge.com/2024/01/13/7-1brc-in-dotnet-even-faster-than-java-cpp/#methodology

**Comment by zamgi** [comment]
thank you for info. 
anyway, i put  text file on real machine with Windows 10 on HDD drive (not SSD).
the file contains not even 10^9, but 10^8 rows.
first start take about 30 sec. 
next starts take less than 1 sec.
this is due to the disk cache starting to work.

i wrote special util for reset windows disk cache. this is in her: https://github.com/zamgi/ReleaseStandbyMemoryPages.
if you run it before running each test, you will be able to observe this behavior: as if your system has just started and the disk cache is empty.

**Comment by zamgi** [comment]
вобщем, вобщем: если запускать все тесты на виртуалках, то там кэширование в ОС будет зависеть от хост-машины и явно влиять на него не получится.
он дело в другом: 
    вот этот тест - "One Billion Row Challenge" - он читает данные с диска и как-то их процессит.
    если его рассматривать как некий реальный сценарий (который вправду может быть, например можно так процессить какие-то безумных размеров логи, которые беруться откуда-то), то в из него нельзя исключать файзу считки данных с диска, а значит кэширование ОС надо учитывать и исключать. иначе как-то однобоко...

**Comment by zamgi** [comment]
что, боишся общаться на родном языке? не очень свобоно в свобоном мире, да?
