### ISSUE TITLE
Measure kpocza's implementation

### ISSUE THREAD

**Issue by kpocza** [buybackoff/1brc#14]
Please measure my implementation [(https://github.com/kpocza/1brc)](https://github.com/kpocza/1brc) and add to the results table if it performs well on you machine.

**Comment by buybackoff** [comment]
Have you run 10K dataset on your side and compared its output with mine or Java?

**Comment by kpocza** [comment]
Fair enough.
Changed the console's output encoding to utf8. Moreover there where sometimes 0.1 differences in avg calculation. Made it more precise. Now I see no differences.

**Comment by buybackoff** [comment]
The blog update is now deploying
