### ISSUE TITLE
Add entry for dzaima

### ISSUE THREAD

**Issue by dzaima** [buybackoff/1brc#17]
https://github.com/dzaima/1brc - build with `make a.out`, run with `THREADS_1BRC=[desired thread count] ./a.out path/to/measurements.txt`.

Language column is mildly non-trivial - there's C, C++, and [Singeli](https://github.com/mlochbaum/Singeli) involved (Singeli generating `gen.c` which is committed to the repo to not require Singeli to build).

I expect it to roughly match lehuyduc's entry on both the original & 10K datasets (on my PC my solution is ~10% faster for 10K, and roughly the same for original).

(the repo also has a Java solution, but it's only optimized for the original dataset, and has extremely high variance (>2x; JIT compilation screwing up? haven't bothered looking into it), and with JIT startup time and worse codegen it struggles even at the best of times, so not worth including)

**Comment by buybackoff** [comment]
You are just in time. I'm creating some automation here:  https://github.com/buybackoff/1brc-bench

And will run lots of CPU core/threads combinations over the weekend on two big Intel/AMD machines.

There are already special cases for @lehuyduc and @austindonisan. It would be great if you could adjust [run.sh](https://github.com/buybackoff/1brc-bench/blob/main/run.sh#L63) as needed.

**Comment by dzaima** [comment]
[here's](https://github.com/dzaima/1brc-bench/commit/4bf5e618cdd0de9512cbfa07637ce5725b79ee51) adding my repo to that; feel free to merge or pick in changes yourself, or request PR

**Comment by buybackoff** [comment]
Great, thank you!

**Comment by dzaima** [comment]
Ok, my solution should now have an aarch64 NEON version, took slightly more time than I expected (though a decent amount was just me being stupid). Should build the same way, but have done only minimal testing and precisely zero tuning (and replaced some manual string comparison with a `memcmp` call, and ~~left semicolon search at a much-less-efficient-than-desired state~~ I went ahead and wrote a saner semicolon search) as my only available aarch64 device is my phone with an A53..
