### ISSUE TITLE
Implement ISpanFormattable on Summary

### ISSUE THREAD

**Issue by sonnemaf** [buybackoff/1brc#8]
Hi,

I think you can win something by implementing ``ISpanFormattable`` on ``Summary``. This will make the string interpolation in ``Console.Write($"{pair.Name}={pair.Value}")`` run faster. You avoid the ToString() method. 

You can try this using this code. It was faster on my (slow) computer. 

```cs
public struct Summary : ISpanFormattable {

    public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider) {
        return destination.TryWrite($"{Min / 10.0:N1}/{Average / 10.0:N1}/{Max / 10.0:N1}", out charsWritten);
    }

    public string ToString(string? format, IFormatProvider? formatProvider) {
        return ToString();
    }
```

If it works you can even gain more performance by reimplementing the TryFormat method without the use of the TryWrite extensionmethod. It quite a lot of work but might work.

Regards,

Fons

**Comment by buybackoff** [comment]
Oh, do you realize that if everything other than `ProcessChunk` was exactly zero then the difference would be less than the noise on my very stable dedicated benchmarking machine!?

**Comment by sonnemaf** [comment]
Are you saying that the Console.Write() is free? Can't imagine that.

**Comment by buybackoff** [comment]
It takes `~ 15-20 msec`. Well, my benchmark resolution is better than that, I will admit that. Will see if the impact is visible.

**Comment by buybackoff** [comment]
Actually I already use that locally, not committed yet. I thought you've implemented Utf8 formatting to a `Span<byte>`.

![image](https://github.com/buybackoff/1brc/assets/489852/501f4a16-c75e-438c-8253-30daabcc45cd)

**Comment by buybackoff** [comment]
I actually like this because it's the right approach. Even if there is not difference in performance. Thank you! 

![image](https://github.com/buybackoff/1brc/assets/489852/7a817509-7162-4dd8-bc04-8b4a9cdeafaf)

![image](https://github.com/buybackoff/1brc/assets/489852/2b4eb8ef-ddb2-4b63-b402-3ad7825ba805)
